### ISSUE TITLE
ERROR:root:Internal Python error in the inspect module.

### ISSUE THREAD

**Issue by skf-git** [kaanaritr/Coursera-GDrive#6]
Hello,

When running 'downloader.download()' I get the following error :

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-ab767c818dcd>", line 1, in <module>
    downloader.download()
  File "/usr/local/lib/python3.8/dist-packages/coursera_gdrive/CourseraDownloader.py", line 285, in download
    self._startDownload()
  File "/usr/local/lib/python3.8/dist-packages/coursera_gdrive/CourseraDownloader.py", line 341, in _startDownload
    self._settings()  # Creates Coursera-dl Configs.
  File "/usr/local/lib/python3.8/dist-packages/coursera_gdrive/CourseraDownloader.py", line 296, in _settings
    with open('coursera-dl.conf', "w") as configFile:
FileNotFoundError: [Errno 2] No such file or directory: 'coursera-dl.conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 2040, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/ultratb.py", line 319, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/ultratb.py", line 353, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.8/inspect.py", line 1515, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/usr/lib/python3.8/inspect.py", line 1473, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.8/inspect.py", line 708, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.8/inspect.py", line 737, in getmodule
    file = getabsfile(object, _filename)
  File "/usr/lib/python3.8/inspect.py", line 721, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/usr/lib/python3.8/posixpath.py", line 379, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
----------------------------------------------------------

Thank you,

**Comment by kaanari** [comment]
Thank you for reporting it. I will look at it soon.
